### ISSUE TITLE
Connect Bitcoin wallet

### ISSUE THREAD

**Issue by lana-shanghai** [keep-starknet-strange/broly#11]
Connect to the Bitcoin wallet via the frontend

**Comment by theanuragg** [comment]
Hey @lana-shanghai Are you open to using wallets that support multiple cryptocurrencies, including Bitcoin (eg:- phantom, backpack)

**Comment by lana-shanghai** [comment]
> Hey @lana-shanghai Are you open to using wallets that support multiple cryptocurrencies, including Bitcoin (eg:- phantom, backpack)

Hey @theanuragg good question, I was thinking about [Xverse](https://chromewebstore.google.com/detail/xverse-wallet/idnnbdplmphpflfnlkomgpfbpcgelopg?hl=en&pli=1) wallet, why would you prefer Phantom?

**Comment by theanuragg** [comment]
it allows u to connect multichain network such as sol, eth

**Comment by theanuragg** [comment]
@lana-shanghai

**Comment by lana-shanghai** [comment]
@theanuragg we are going to connect only to Starknet and Bitcoin (to Starknet for the user to connect and deposit the fees and to Bitcoin in order to fetch the address where the user wants to receive the inscription in the end), we don't need to connect to any other ecosystems
